spring:
  application:
    name: SPRING PROJECT MAY 2024
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "admin"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
bot:
  token: 7505475411:AAFkEQ6UwdZ08n8Vl7TBJCS8Pu0siKC_aLM
  username: MyDemoCryptoBot
